version: '3.8'

services:
  db: 
    image: 'postgres:15.3-alpine'
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./.docker/data:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_PORT}:5432"

  
  
