import Head from "next/head";
import Link from "next/link";

import { routes } from "~/constants/routes"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Link href={routes.auth.signIn}>Sign in</Link>
        <Link href={routes.auth.signUp}>Sign up</Link>

      </main>
    </>
  );
}

