import Head from "next/head";
import Link from "next/link";
import { routes } from "~/constants/routes"
import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading, refetch } = api.auth.testSignedIn.useQuery(undefined, { enabled: false })

  console.log({ data, isLoading })

  const handleFetchProtected = async () => {
    await refetch()
  }


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Link href={routes.auth.signIn}>Sign in</Link>
        <Link href={routes.auth.signUp}>Sign up</Link>

        <button type="button" className="btn-primary" onClick={handleFetchProtected}>Click if u are auth</button>
      </main>
    </>
  );
}

